AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS Lambda function for image generation using AWS SAM.
  Provides endpoints for generating images and serving a static HTML page.

Globals:
  Function:
    Timeout: 30
    Runtime: python3.9
    MemorySize: 256
    Environment:
      Variables:
        BUCKET_NAME: pgr301-couch-explorers
        CANDIDATE_NUMBER: 8
    LoggingConfig:
      LogFormat: JSON

Resources:
  ImageGeneratorProFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ImagenLambda/
      Handler: app.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource: arn:aws:s3:::pgr301-couch-explorers/*
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: '*'
      Events:
        GenerateImageApi:
          Type: Api
          Properties:
            Path: /generate
            Method: post
        StaticPageApi:
          Type: Api
          Properties:
            Path: /
            Method: get

Outputs:
  ApiUrl:
    Description: Base URL for API Gateway
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  GenerateImageApiUrl:
    Description: URL for the Generate Image endpoint
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/generate/"
  FunctionArn:
    Description: ARN of the ImageGeneratorPro Lambda function
    Value: !GetAtt ImageGeneratorProFunction.Arn
