name: Build and Publish Docker Container

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual trigger

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Step 3: Build the Docker image
      - name: Build Docker Image
        working-directory: ImagenGeneratorPro
        run: |
          docker build -t nisjety/java-sqs-client:latest -f Dockerfile .

      # Step 4: Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push nisjety/java-sqs-client:latest

  test-docker:
    runs-on: ubuntu-latest
    needs: build-and-publish # Ensure the image is built before testing

    steps:
      # Step 1: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Step 2: Pull the Docker image
      - name: Pull Docker Image
        run: |
          docker pull nisjety/java-sqs-client:latest

      # Step 3: Run the Docker container with environment variables
      - name: Run Docker Container
        run: |
          docker run \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -
